# Generated by Django 4.1.7 on 2023-02-17 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField()),
                ('patient_age', models.IntegerField()),
                ('ppointment_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_attended', models.BooleanField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
