# Generated by Django 4.1.7 on 2023-02-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='ppointment_datetime',
            new_name='appointment_datetime',
        ),
    ]
