# Generated by Django 4.1.7 on 2023-02-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_ppointment_datetime_appointment_appointment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinic',
        ),
    ]
