# Generated by Django 4.1.7 on 2023-02-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clincs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='department',
            field=models.CharField(choices=[('Heart Center', 'Heart Center'), ('Neuroscience Center', 'Neuroscience Center'), ('Obesity Center', 'Obesity Center'), ('Eye Center', 'Eye Center'), ('Orthopedic Center', 'Orthopedic Center'), ('Pediatric Center', 'Pediatric Center')], default='Department', max_length=50),
        ),
    ]
