# Generated by Django 4.1.7 on 2023-02-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('feature_image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('department', models.TextField()),
                ('established_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField()),
                ('patient_age', models.IntegerField()),
                ('appointment_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_attended', models.BooleanField(default=False)),
                ('clinics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinics')),
            ],
        ),
    ]
