# Generated by Django 4.1.7 on 2023-02-18 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='department',
            field=models.CharField(choices=[('HC', 'Heart Center'), ('NC', 'Neuroscience Center'), ('OC', 'Obesity Center'), ('ORC', 'Orthopedic Center'), ('PC', 'Pediatric Center')], default='HC', max_length=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='established_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
