# Generated by Django 4.1.7 on 2023-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_clinic_department_clinic_established_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.ImageField(default=20, upload_to=''),
        ),
    ]
