# Generated by Django 4.1.7 on 2023-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0009_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
