# Generated by Django 4.1.6 on 2023-02-19 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('established_at', models.DateField(default=django.utils.timezone.now)),
                ('department', models.CharField(choices=[('HC', 'Heart Center'), ('NC', 'Neuroscience Center'), ('OC', 'Obesity Center'), ('ORC', 'Orthopedic Center'), ('PC', 'Pediatric Center')], default='HC', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.ImageField(default=20, upload_to='')),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_attended', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
