# Generated by Django 4.1.7 on 2023-02-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='department',
            field=models.CharField(choices=[('HC', 'Heart Center'), ('NC', 'Neuroscience Center'), ('OBC', 'Obesity Center'), ('EC', 'Eye Center'), ('ORC', 'Orthopedic Center'), ('PC', 'Pediatric Center')], default='', max_length=30),
        ),
    ]
