# Generated by Django 4.1.7 on 2023-02-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinc',
            name='departments',
            field=models.CharField(choices=[('HC', 'HeartCenter'), ('NC', 'NeuroscienceCenter'), ('OC', 'ObesityCenter'), ('EC', 'EyeCenter'), ('OcC', 'OrthopedicCenter')], default='NL', max_length=3),
        ),
    ]
