# Generated by Django 4.1.5 on 2023-02-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apclinec',
            new_name='Relation_clinic',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentUser',
            new_name='Relation_user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_attended',
            field=models.BooleanField(),
        ),
    ]
