# Generated by Django 4.1.7 on 2023-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='department',
            field=models.CharField(choices=[('heart_center', 'Heart Center'), ('neuroscience_center', 'Neuroscience Center'), ('Obesity_center', 'Obesity Center'), ('Eye_center', 'Eye Center'), ('Orthopedic_center', 'Orthopedic Center'), ('Pediatric_center', 'Pediatric Center')], max_length=20),
        ),
    ]
