# Generated by Django 4.1.7 on 2023-02-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clinic_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=models.TextField(),
        ),
    ]
