# Generated by Django 4.1.7 on 2023-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clinic_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='department',
            field=models.CharField(choices=[('Heart_Center', 'Heart Center'), ('Neuroscience_Center', 'Neuroscience Center'), ('Obesity_Center', 'Obesity Center'), ('Eye_Center', 'Eye Center'), ('Orthopedic_Center', 'Orthopedic Center'), ('Pediatric_Center', 'Pediatric Center')], default='', max_length=50),
        ),
    ]
