# Generated by Django 4.1.7 on 2023-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clinic_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='department',
            field=models.CharField(choices=[('Heart Center', 'Heart Center'), ('Neuroscience Center', 'Neuroscience Center'), ('Obesity Center', 'Obesity Center'), ('Eye Center', 'Eye Center'), ('Orthopedic Center', 'Orthopedic Center'), ('Pediatric Center', 'Pediatric Center')], max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='feature_image',
            field=models.ImageField(upload_to='clinics/'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
