# Generated by Django 4.1.7 on 2023-02-17 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('feature_image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('departments', models.CharField(choices=[('HC', 'HeartCenter'), ('NC', 'NeuroscienceCenter'), ('OC', 'ObesityCenter'), ('EC', 'EyeCenter'), ('OcC', 'OrthopedicCenter')], default='NL', max_length=3)),
                ('established_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField()),
                ('patient_age', models.IntegerField()),
                ('appointment_datetime', models.DateField()),
                ('is_attended', models.BooleanField(default=False)),
                ('apclinec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('appointmentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
