# Generated by Django 4.1.5 on 2023-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='department',
            field=models.CharField(choices=[('HC', 'Heart Center'), ('NC', 'Neuroscience Center'), ('OC', 'Obesity Center'), ('EC', 'Eye Center'), ('ORC', 'Orthopedic Center'), ('PC', 'Pediatric Center')], max_length=300),
        ),
    ]
