# Generated by Django 4.1.7 on 2023-02-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
