# Generated by Django 4.1.7 on 2023-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_appointment_clinic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic_name',
            field=models.CharField(max_length=1024),
        ),
    ]
