# Generated by Django 4.1.7 on 2023-02-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_appointment_clinic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
    ]
